name: Build with BuildKit

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image with BuildKit
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.cn-beijing.aliyuncs.com/llaoj/kubespray:${{ github.ref_name }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
