name: build image

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-**"

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  IMAGE_REPO: llaoj/kubespray
  TAG: ${{ github.ref_name }}
  DOCKERFILE: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker credentials
        run: |
          mkdir -p $(pwd)/kaniko/.docker
          echo "{\"auths\":{\"${{ env.REGISTRY }}\":{\"auth\":\"$(echo -n '${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_PASSWORD }}' | base64)\"}}}" > $(pwd)/kaniko/.docker/config.json

      - name: Build and push image using Kaniko
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -v $(pwd)/kaniko/.docker:/kaniko/.docker \
            gcr.io/kaniko-project/executor:debug \
            --context=dir:///workspace \
            --dockerfile=/workspace/${{ env.DOCKERFILE }} \
            --destination=${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.TAG }} \
            --cache=true

